<?php

namespace Cms\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\Stdlib\RequestInterface as Request;
use Zend\Stdlib\ResponseInterface as Response;
use Zend\View\Model\ViewModel;

class AuthController extends AbstractActionController
{

    public function onDispatch(MvcEvent $e)
    {
        $this->layout()->setTemplate('layout/auth');
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

    public function autenticacaoAction()
    {
        return new ViewModel();
    }

    public function recuperarSenhaAction()
    {
        return new ViewModel();
    }

    public function redefinirSenhaAction()
    {
        return new ViewModel();
    }
}
