<?= $this->doctype() ?>
<html lang="en">

<head>
    <?= $this->headTitle('Teste Prático Treinacon')->setSeparator(' - ')->setAutoEscape(FALSE) ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Teste Prático Treinacon">
    <meta name="author" content="Flávio Souza">

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath(PATH_TEMPLATE . "vendor/bootstrap/css/bootstrap.min.css"))
        ->prependStylesheet($this->basePath(PATH_TEMPLATE . "vendor/font-awesome/css/font-awesome.min.css"))
        ->prependStylesheet($this->basePath(PATH_TEMPLATE . "css/sb-admin.css"))
    ?>
    <?= $this->headScript()
        ->prependFile($this->basePath(PATH_TEMPLATE . "vendor/jquery-easing/jquery.easing.min.js"))
        ->prependFile($this->basePath(PATH_TEMPLATE . "vendor/bootstrap/js/bootstrap.bundle.min.js"))
        ->prependFile($this->basePath("js/auth.js"))
        ->prependFile($this->basePath("libs/sweetalert.min.js"))
        ->prependFile($this->basePath(PATH_TEMPLATE . "vendor/jquery/jquery.min.js"))
    ?>
</head>

<body class="bg-dark">
<div class="container">
    <?= $this->content ?>
</div>

</body>

</html>
