<?= $this->doctype() ?>

<!DOCTYPE html>
<html lang="en">

<head>
    <?= $this->headTitle('Teste Prático Treinacon')->setSeparator(' - ')->setAutoEscape(FALSE) ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Teste Prático Treinacon">
    <meta name="author" content="Flávio Souza">

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath(PATH_TEMPLATE . "vendor/bootstrap/css/bootstrap.min.css"))
        ->prependStylesheet($this->basePath(PATH_TEMPLATE . "vendor/font-awesome/css/font-awesome.min.css"))
        ->prependStylesheet($this->basePath(PATH_TEMPLATE . "css/sb-admin.css"))
        ->prependStylesheet($this->basePath("css/cms.css"))
    ?>

    <?= $this->headScript()
        ->prependFile($this->basePath(PATH_TEMPLATE . "vendor/jquery-easing/jquery.easing.min.js"))
        ->prependFile($this->basePath(PATH_TEMPLATE . "js/sb-admin.min.js"))
        ->prependFile($this->basePath("js/crud.js"))
        ->prependFile($this->basePath(PATH_TEMPLATE . "vendor/bootstrap/js/bootstrap.bundle.min.js"))
        ->prependFile($this->basePath(PATH_TEMPLATE . "vendor/jquery/jquery.min.js"))
    ?>

</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="index.html">Treinacon</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href="index.html">
                    <i class="fa fa-fw fa-dashboard"></i>
                    <span class="nav-link-text">Dashboard</span>
                </a>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Usuários">
                <a class="nav-link" href="charts.html">
                    <i class="fa fa-fw fa-users"></i>
                    <span class="nav-link-text">Usuários</span>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">

            <li class="nav-item">
                <a href="<?php echo $this->url('sair'); ?>">
                    <i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper">
    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="index.html">Dashboard</a>
            </li>
            <li class="breadcrumb-item active">Blank Page</li>
        </ol>
        <div class="row">
            <div class="col-12">
                <?= $this->content ?>
            </div>
        </div>
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
        <div class="container">
            <div class="text-center">
                <small>Desenvolvido por Flávio Souza</small>
            </div>
        </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

</div>
</body>

</html>
