<?php $title = (int)$form->get('id')->getValue() > 0 ? 'Editar Usuário' : 'Cadastrar Usuário'; ?>
<?php $this->headTitle($title); ?>
<div class="card">
    <div class="card-header">
        <i class="fa fa-users"></i> <?php echo $title ?>
    </div>
    <div class="card-body">
        <?php $form->prepare(); ?>
        <?php echo $this->form()->openTag($form); ?>
        <div class="row">
            <div class="form-group col-4">
                <?php echo $this->formLabel($form->get('nome')); ?>
                <?php echo $this->formElement($form->get('nome')); ?>
            </div>
            <div class="form-group col-5">
                <?php echo $this->formLabel($form->get('email')); ?>
                <?php echo $this->formElement($form->get('email')); ?>
            </div>
            <div class="form-group col-3">
                <?php echo $this->formLabel($form->get('senha')); ?>
                <?php echo $this->formElement($form->get('senha')); ?>
            </div>
        </div>
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <?php echo $this->formHidden($form->get('id')); ?>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>

