<?php $this->headTitle('Listagem de Usuários'); ?>


<pre>
    <?php
    print_r($this->params()->fromQuery('busca'));
    ?>
</pre>
<div class="card">
    <div class="card-header">
        <i class="fa fa-users"></i> Usuários
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                <form>
                    <div class="row">
                        <div class="col-lg-4">
                            <input class="form-control" placeholder="Buscar por nome.." name="busca">
                        </div>
                        <div class="col-lg-2">
                            <button type="submit" class="btn btn-outline-primary btn-block">Buscar</button>
                        </div>
                        <div class="col-lg-6 text-right">
                            <a href="<?php echo $this->url('usuario', ['action' => 'cadastrar']); ?>"
                               class="btn btn-outline-success">
                                <i class="fa fa-plus"></i> Adicionar
                            </a>
                        </div>

                    </div>
                </form>
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered table-sm" id="listagem">
                            <thead>
                            <tr role="row">
                                <th>Id</th>
                                <th>Nome</th>
                                <th>E-mail</th>
                                <th class="acoes">Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if (count($lista) <= 0): ?>
                                <tr class="text-danger">
                                    <th colspan="999">Nenhum registro encontrado.</th>
                                </tr>
                            <?php endif; ?>
                            <?php foreach ($lista as $item): ?>
                                <tr role="row">
                                    <td><?php echo $item->id; ?></td>
                                    <td><?php echo $item->nome; ?></td>
                                    <td><?php echo $item->email; ?></td>
                                    <td class="acoes">
                                        <a href="<?= $this->url('usuario', ['action' => 'editar', 'id' => $item->id]) ?>"
                                           class="btn btn-outline-primary" title="Editar Usuário">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <?php $url = $this->url('usuario', ['action' => 'excluir', 'id' => $item->id]); ?>
                                        <a href="javascript:;" onclick="CRUD.excluir('<?php echo $url ?>')"
                                           class="btn btn-outline-danger" title="Remover Usuário">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-12">
                        <?php echo $this->paginationControl($lista, 'Sliding', 'partials/pagination.phtml'); ?>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>