<?php $this->headTitle('Listagem de Usuários'); ?>
<div class="card">
    <div class="card-header">
        <i class="fa fa-users"></i> Usuários
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                <div class="row">
                    <div class="col-lg-12 text-right">
                        <a href="<?php echo $this->url('usuario', ['action' => 'cadastrar']); ?>"
                           class="btn btn-success btn-sm">
                            <i class="fa fa-plus"></i> Adicionar
                        </a>
                    </div>

                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered table-sm" id="listagem">
                            <thead>
                            <tr role="row">
                                <th>Id</th>
                                <th>Nome</th>
                                <th>E-mail</th>
                                <th class="acoes">Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if (count($lista) <= 0): ?>
                                <tr class="text-danger">
                                    <th colspan="999">Nenhum registro encontrado.</th>
                                </tr>
                            <?php endif; ?>
                            <?php foreach ($lista as $item): ?>
                                <tr role="row">
                                    <td><?php echo $item->id; ?></td>
                                    <td><?php echo $item->nome; ?></td>
                                    <td><?php echo $item->email; ?></td>
                                    <td class="acoes">
                                        <a href="<?= $this->url('usuario', ['action' => 'editar', 'id' => $item->id]) ?>"
                                           class="btn btn-primary btn-sm" title="Editar Usuário">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <?php $url = $this->url('usuario', ['action' => 'excluir', 'id' => $item->id]); ?>
                                        <a href="javascript:;" onclick="CRUD.excluir('<?php echo $url ?>')"
                                           class="btn btn-danger btn-sm" title="Remover Usuário">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-7">
                        <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
                            <ul class="pagination">
                                <li class="paginate_button page-item previous" id="dataTable_previous"><a href="#"
                                                                                                          aria-controls="dataTable"
                                                                                                          data-dt-idx="0"
                                                                                                          tabindex="0"
                                                                                                          class="page-link">Previous</a>
                                </li>
                                <li class="paginate_button page-item "><a href="#" aria-controls="dataTable"
                                                                          data-dt-idx="1" tabindex="0"
                                                                          class="page-link">1</a></li>
                                <li class="paginate_button page-item active"><a href="#" aria-controls="dataTable"
                                                                                data-dt-idx="2" tabindex="0"
                                                                                class="page-link">2</a></li>
                                <li class="paginate_button page-item "><a href="#" aria-controls="dataTable"
                                                                          data-dt-idx="3" tabindex="0"
                                                                          class="page-link">3</a></li>
                                <li class="paginate_button page-item "><a href="#" aria-controls="dataTable"
                                                                          data-dt-idx="4" tabindex="0"
                                                                          class="page-link">4</a></li>
                                <li class="paginate_button page-item "><a href="#" aria-controls="dataTable"
                                                                          data-dt-idx="5" tabindex="0"
                                                                          class="page-link">5</a></li>
                                <li class="paginate_button page-item "><a href="#" aria-controls="dataTable"
                                                                          data-dt-idx="6" tabindex="0"
                                                                          class="page-link">6</a></li>
                                <li class="paginate_button page-item next" id="dataTable_next"><a href="#"
                                                                                                  aria-controls="dataTable"
                                                                                                  data-dt-idx="7"
                                                                                                  tabindex="0"
                                                                                                  class="page-link">Next</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>