<div class="card card-login mx-auto mt-5">
    <div class="card-header">Autenticação</div>
    <div class="card-body">
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Email</label>
                <input class="form-control" id="exampleInputEmail1" type="email" aria-describedby="emailHelp">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Senha</label>
                <input class="form-control" id="exampleInputPassword1" type="password">
            </div>
            <a class="btn btn-primary btn-block" href="index.html">Login</a>
        </form>
        <div class="text-center">
            <a class="d-block small mt-3" href="<?= $this->url('recuperar-senha') ?>">Recuperar Senha</a>
        </div>
    </div>
</div>