<div class="card card-login mx-auto mt-5">
    <div class="card-header">Recuperar senha</div>
    <div class="card-body">
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Email</label>
                <input class="form-control" id="exampleInputEmail1" type="email">
            </div>
            <a class="btn btn-primary btn-block" href="index.html">Recuperar</a>
        </form>
    </div>
</div>