<div class="card card-login mx-auto mt-5">
    <div class="card-header">Redefina sua senha</div>
    <div class="card-body">
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Senha</label>
                <input class="form-control" id="exampleInputEmail1" type="password">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Repita a senha</label>
                <input class="form-control" id="exampleInputEmail1" type="password">
            </div>
            <a class="btn btn-primary btn-block" href="index.html">Redefinir</a>
        </form>
    </div>
</div>